env:
  node: true

parserOptions:
  ecmaVersion: 6

extends:
  - eslint:recommended
  - plugin:node/recommended

rules:
  valid-jsdoc: 0
  func-style: 0
  no-use-before-define: 0
  camelcase: 1
  no-unused-vars: 2
  no-alert: 2
  no-console: [2, { allow: ['warn', 'error'] }]
  no-underscore-dangle: 0

  strict: [2, 'global']
  no-var: 2
  prefer-arrow-callback: 2
  prefer-const: 2
  no-inner-declarations: 0
  object-shorthand: [2, 'consistent-as-needed']
  newline-per-chained-call: 2

  node/no-deprecated-api: 0
