language: node_js

sudo: false

# test on node.js versions
node_js:
  - '10'
  - '8'
  - '6'

services:
  - redis-server

script:
  - npm run prettier -- --list-different
  - npm run test

after_script:
  - npm run coveralls
